image: nixos/nix:latest

variables:
  # Pinned 2020-01-01.
  NIX_PATH: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/b0bbacb52134a7e731e549f4c0a7a2a39ca6b481.tar.gz"

stages:
  - test
  - deploy

Run tests:
  stage: test
  script:
    - nix-shell tests -A run.files-text
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always

pages:
  stage: deploy
  script:
    - mkdir -p ~/.config/nixpkgs
    - echo '{ manual.html.enable = true; }' > ~/.config/nixpkgs/home.nix
    - nix-shell . -A install
    - mkdir public
    - cp -r ~/.nix-profile/share/doc/home-manager/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always

Deploy NUR:
  stage: deploy
  variables:
    HM_BRANCH: $CI_COMMIT_REF_NAME
    HM_COMMIT_SHA: $CI_COMMIT_SHA
  trigger:
    project: rycee/nur-expressions
    branch: master
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH =~ /^release-/
      when: always
